@startuml Entity-Relationship-Diagram
entity "Customer" as customer {
  * customer_id : int <<PK>>
  --
  * name : varchar
}

entity "PizzaOrder" as PO {
  * order_id : int <<PK>>
  --
  * customer_id : int <<FK>>
  * customer_id : int 
  * order_date : datetime
  * total_amount : decimal
}
entity "Pizza" as P {
  * pizza_id : INT <<PK>>
  --
  name : VARCHAR
  size : VARCHAR
  price : DECIMAL
}
entity "Ingredient" as I {
  * ingredient_id : INT <<PK>>
  --
  name : VARCHAR
  quantity : VARCHAR
}
entity "OrderItem" as OI {
  * order_item_id : int <<PK>>
  --
  * order_id : int <<FK>>
  * pizza_id : int <<FK>>
  * quantity : int
  * price : decimal
}
entity "DeliveryPerson" as DP {
  * delivery_person_id : int <<PK>>
  --
  * name : varchar
}
entity "DiscountCode" as DC {
  * discount_id : int <<PK>>
  --
  * percentage : decimal
  * expiry_date : datetime
}
customer ||--o{ PO : places
PO }o--o{ P : contains

@enduml

